### ISSUE TITLE
Syntax highlighting for code snippets

### ISSUE THREAD

**Issue by mrblackus** [cedricss/photon-book-creator#1]
It really lacks of syntax highlighting for code snippets. One lightweight solution could be to integrate [PrismJS](https://github.com/PrismJS/prism).
As you are already using `<pre>` and `<code>` tag, just integrating the Prism javascript file will do the stuff. ;)

**Comment by cedricss** [comment]
Thanks for the suggestion! It's now available in **Photon Book Creator 1.3**

Examples:
- [Monokai theme](http://cedricss.github.io/photon-book-creator/page-1.html#section-3)
- [Github theme](http://wakanda.github.io/wakanda-studio/sass-precompilation.html#add-sass-precompilation-to-your-web-app)

I also included a `vs` theme (the default Visual Studio theme).

PS. I use [Rouge](http://rouge.jneen.net/) to provide syntax highlighting at compile time (long term vision for Photon Book Creator is the generation of books in various format: html, ebook, pdf...).
